services:
  builder:
    build:
      context: .
    tty: true
    user: ubuntu
    volumes:
      - ../layers/:/home/ubuntu/shared/layers:ro
      - ../scripts/:/home/ubuntu/shared/scripts:ro
    working_dir: /home/ubuntu/shared
    environment:
      - TZ=Asia/Tokyo
