services:
  builder:
    build:
      context: .
    tty: true
    user: ubuntu
    volumes:
      - ..:/home/ubuntu/shared
    working_dir: /home/ubuntu/shared
    environment:
      - TZ=Asia/Tokyo
